
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int llaveC = 10;
  public static final int llaveA = 9;
  public static final int coma = 13;
  public static final int claves = 6;
  public static final int registros = 7;
  public static final int cadena = 5;
  public static final int digito = 3;
  public static final int decimal = 4;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int corC = 12;
  public static final int corA = 11;
  public static final int identificador = 2;
  public static final int igual = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "identificador",
  "digito",
  "decimal",
  "cadena",
  "claves",
  "registros",
  "igual",
  "llaveA",
  "llaveC",
  "corA",
  "corC",
  "coma"
  };
}

