/* The following code was generated by JFlex 1.7.0 */

/*----------------------------------------------------------------------------
--------------------- 1ra. Area: Codigo de Usuario
----------------------------------------------------------------------------*/

//-------> Paquete, importaciones

package Analizador2;

import java_cup.runtime.*;
import java.util.ArrayList;



/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>src/Analizador2/Lexico2.jflex</tt>
 */
public class Lexico2 implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int COMENT_SIMPLE = 2;
  public static final int COMENT_MULTI = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  8, 11,  2,  2,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     2, 44,  7,  0,  0,  0,  0,  0, 40, 41, 10,  0, 36,  0,  4,  9, 
     3,  3,  3,  3,  3,  3,  3,  3,  3,  3, 45, 39, 42, 33, 43,  0, 
     0, 12, 30, 14, 29, 21, 32, 31, 15, 17,  5,  5, 20, 24, 22, 19, 
    28,  5, 13, 26, 27, 23, 18,  5,  5,  5,  5, 34,  0, 35,  0,  6, 
     0, 12, 30, 14, 29, 21, 32, 31, 15, 17,  5,  5, 20, 24, 22, 19, 
    28,  5, 13, 26, 27, 23, 18,  5,  5,  5,  5, 37,  1, 38,  0,  0, 
     0,  0,  0,  0,  0, 11,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  5,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  5,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\2\2\1\3\1\4\2\1\2\4\1\1"+
    "\4\4\1\1\3\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\2\1\23\2\0\1\24\1\25\1\26\3\4"+
    "\1\0\4\4\1\0\3\4\1\22\1\27\3\4\1\0"+
    "\4\4\1\0\6\4\1\0\4\4\1\0\3\4\1\0"+
    "\3\4\1\0\4\4\2\30\1\4\1\0\1\4\1\0"+
    "\1\4\1\31\1\32\1\0\3\4\1\0\2\4\1\0"+
    "\1\4\2\33\1\0\1\4\1\0\3\4\1\0\1\4"+
    "\1\0\1\4\1\0\1\4\2\34\2\35\1\0\2\4"+
    "\2\36\2\37\2\40\2\41\1\0\1\4\1\0\1\4"+
    "\2\42";

  private static int [] zzUnpackAction() {
    int [] result = new int[142];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\56\0\134\0\212\0\212\0\270\0\346\0\u0114"+
    "\0\u0142\0\u0170\0\u019e\0\u01cc\0\u01fa\0\u0228\0\u0256\0\u0284"+
    "\0\u02b2\0\u02e0\0\u030e\0\u033c\0\u036a\0\212\0\212\0\212"+
    "\0\212\0\212\0\212\0\212\0\212\0\212\0\212\0\212"+
    "\0\212\0\212\0\270\0\u0398\0\270\0\u03c6\0\u0142\0\212"+
    "\0\212\0\212\0\u03f4\0\u0422\0\u0450\0\u047e\0\u04ac\0\u04da"+
    "\0\u0508\0\u0536\0\u0564\0\u0592\0\u05c0\0\u05ee\0\212\0\u03c6"+
    "\0\u061c\0\u064a\0\u0678\0\u06a6\0\u06d4\0\u0702\0\u0730\0\u075e"+
    "\0\u078c\0\u07ba\0\u07e8\0\u0816\0\u0844\0\u0872\0\u08a0\0\u08ce"+
    "\0\u08fc\0\u092a\0\u0958\0\u0986\0\u09b4\0\u09e2\0\u0a10\0\u0a3e"+
    "\0\u0a6c\0\u0a9a\0\u0ac8\0\u0af6\0\u0b24\0\u0b52\0\u0b80\0\u0bae"+
    "\0\u0bdc\0\212\0\u0114\0\u0c0a\0\u0c38\0\u0c66\0\u0c94\0\u0cc2"+
    "\0\u0114\0\u0cf0\0\u0d1e\0\u0d4c\0\u0d7a\0\u0da8\0\u0dd6\0\u0e04"+
    "\0\u0e32\0\u0e60\0\u0e8e\0\212\0\u0114\0\u0ebc\0\u0eea\0\u0f18"+
    "\0\u0f46\0\u0f74\0\u0fa2\0\u0fd0\0\u0ffe\0\u102c\0\u105a\0\u1088"+
    "\0\u10b6\0\212\0\u0114\0\212\0\u0114\0\u10e4\0\u1112\0\u1140"+
    "\0\212\0\u0114\0\212\0\u0114\0\212\0\u0114\0\212\0\u0114"+
    "\0\u116e\0\u119c\0\u11ca\0\u11f8\0\212\0\u0114";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[142];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\1\6\1\7\1\4\1\10\1\4\1\11"+
    "\1\6\1\12\1\4\1\0\1\13\1\10\1\14\1\10"+
    "\1\15\1\16\1\10\1\17\1\20\1\10\1\21\2\10"+
    "\1\22\1\23\1\10\1\24\2\10\1\25\1\10\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\2\5\1\6\5\5\1\43"+
    "\47\5\1\6\5\5\1\6\1\5\1\44\1\0\42\5"+
    "\60\0\1\45\5\0\1\45\50\0\1\7\1\46\54\0"+
    "\1\10\1\0\2\10\5\0\4\10\1\0\10\10\1\0"+
    "\7\10\15\0\7\47\1\50\46\47\11\0\1\51\1\52"+
    "\46\0\1\10\1\0\2\10\5\0\1\10\1\53\2\10"+
    "\1\0\10\10\1\0\7\10\20\0\1\10\1\0\2\10"+
    "\5\0\1\54\3\10\1\0\2\10\1\55\5\10\1\0"+
    "\7\10\45\0\1\56\30\0\1\10\1\0\2\10\5\0"+
    "\4\10\1\0\7\10\1\57\1\0\7\10\20\0\1\10"+
    "\1\0\2\10\5\0\4\10\1\0\10\10\1\0\4\10"+
    "\1\60\2\10\20\0\1\10\1\0\2\10\5\0\4\10"+
    "\1\0\4\10\1\61\3\10\1\0\7\10\20\0\1\10"+
    "\1\0\2\10\5\0\4\10\1\0\6\10\1\62\1\10"+
    "\1\0\7\10\44\0\1\63\31\0\1\10\1\0\2\10"+
    "\5\0\4\10\1\0\6\10\1\64\1\10\1\0\7\10"+
    "\20\0\1\10\1\0\2\10\5\0\1\10\1\65\2\10"+
    "\1\0\10\10\1\0\7\10\20\0\1\10\1\0\2\10"+
    "\5\0\1\10\1\66\2\10\1\0\10\10\1\0\7\10"+
    "\26\0\1\67\47\0\1\70\55\0\1\10\1\0\2\10"+
    "\5\0\2\10\1\71\1\10\1\0\10\10\1\0\7\10"+
    "\20\0\1\10\1\0\2\10\5\0\4\10\1\0\10\10"+
    "\1\0\3\10\1\72\3\10\20\0\1\10\1\0\2\10"+
    "\5\0\4\10\1\0\5\10\1\73\2\10\1\0\7\10"+
    "\51\0\1\74\24\0\1\10\1\0\2\10\5\0\4\10"+
    "\1\0\10\10\1\0\2\10\1\75\4\10\20\0\1\10"+
    "\1\0\2\10\5\0\4\10\1\0\10\10\1\0\1\10"+
    "\1\76\5\10\20\0\1\10\1\0\2\10\5\0\4\10"+
    "\1\0\4\10\1\77\3\10\1\0\7\10\20\0\1\10"+
    "\1\0\2\10\5\0\4\10\1\0\7\10\1\100\1\0"+
    "\7\10\45\0\1\101\30\0\1\10\1\0\2\10\5\0"+
    "\4\10\1\0\7\10\1\102\1\0\7\10\20\0\1\10"+
    "\1\0\2\10\5\0\4\10\1\0\2\10\1\103\5\10"+
    "\1\0\7\10\20\0\1\10\1\0\2\10\5\0\1\104"+
    "\3\10\1\0\10\10\1\0\7\10\20\0\1\10\1\0"+
    "\2\10\5\0\3\10\1\105\1\0\10\10\1\0\7\10"+
    "\20\0\1\10\1\0\2\10\5\0\4\10\1\0\4\10"+
    "\1\106\3\10\1\0\7\10\20\0\1\10\1\0\2\10"+
    "\5\0\4\10\1\0\10\10\1\0\1\10\1\107\5\10"+
    "\32\0\1\110\43\0\1\10\1\0\2\10\5\0\1\10"+
    "\1\111\2\10\1\0\10\10\1\0\7\10\20\0\1\10"+
    "\1\0\2\10\5\0\4\10\1\0\4\10\1\112\3\10"+
    "\1\0\7\10\20\0\1\10\1\0\2\10\5\0\1\10"+
    "\1\113\2\10\1\0\10\10\1\0\7\10\20\0\1\10"+
    "\1\0\2\10\5\0\4\10\1\0\4\10\1\114\3\10"+
    "\1\0\7\10\31\0\1\115\44\0\1\10\1\0\2\10"+
    "\5\0\1\116\3\10\1\0\10\10\1\0\7\10\20\0"+
    "\1\10\1\0\2\10\5\0\4\10\1\0\7\10\1\117"+
    "\1\0\7\10\20\0\1\10\1\0\2\10\5\0\4\10"+
    "\1\0\10\10\1\0\6\10\1\120\20\0\1\10\1\0"+
    "\2\10\5\0\4\10\1\121\1\122\7\10\1\0\7\10"+
    "\20\0\1\10\1\0\2\10\5\0\4\10\1\0\5\10"+
    "\1\123\2\10\1\0\7\10\20\0\1\10\1\0\2\10"+
    "\5\0\1\124\3\10\1\0\10\10\1\0\7\10\35\0"+
    "\2\125\37\0\1\10\1\0\2\10\5\0\4\10\1\125"+
    "\1\126\7\10\1\0\7\10\20\0\1\10\1\0\2\10"+
    "\5\0\4\10\1\0\5\10\1\127\2\10\1\0\7\10"+
    "\20\0\1\10\1\0\2\10\5\0\1\130\3\10\1\0"+
    "\10\10\1\0\7\10\20\0\1\10\1\0\2\10\5\0"+
    "\1\10\1\131\2\10\1\0\10\10\1\0\7\10\32\0"+
    "\1\132\43\0\1\10\1\0\2\10\5\0\1\10\1\133"+
    "\2\10\1\0\10\10\1\0\7\10\20\0\1\10\1\0"+
    "\2\10\5\0\4\10\1\0\4\10\1\134\3\10\1\0"+
    "\7\10\20\0\1\10\1\0\2\10\5\0\4\10\1\135"+
    "\1\136\7\10\1\0\7\10\37\0\1\137\36\0\1\10"+
    "\1\0\2\10\5\0\4\10\1\0\1\10\1\140\6\10"+
    "\1\0\7\10\20\0\1\10\1\0\2\10\5\0\1\141"+
    "\3\10\1\0\10\10\1\0\7\10\20\0\1\10\1\0"+
    "\2\10\5\0\1\10\1\142\2\10\1\0\10\10\1\0"+
    "\7\10\45\0\1\143\30\0\1\10\1\0\2\10\5\0"+
    "\4\10\1\0\7\10\1\144\1\0\7\10\20\0\1\10"+
    "\1\0\2\10\5\0\4\10\1\0\4\10\1\145\3\10"+
    "\1\0\7\10\20\0\1\10\1\0\2\10\5\0\1\10"+
    "\1\146\2\10\1\0\10\10\1\0\7\10\20\0\1\10"+
    "\1\0\2\10\5\0\4\10\1\147\1\150\7\10\1\0"+
    "\7\10\20\0\1\10\1\0\2\10\5\0\4\10\1\0"+
    "\10\10\1\0\3\10\1\151\3\10\33\0\1\152\42\0"+
    "\1\10\1\0\2\10\5\0\2\10\1\153\1\10\1\0"+
    "\10\10\1\0\7\10\40\0\1\154\35\0\1\10\1\0"+
    "\2\10\5\0\4\10\1\0\2\10\1\155\5\10\1\0"+
    "\7\10\20\0\1\10\1\0\2\10\5\0\4\10\1\0"+
    "\10\10\1\156\1\157\6\10\35\0\2\160\37\0\1\10"+
    "\1\0\2\10\5\0\4\10\1\160\1\161\7\10\1\0"+
    "\7\10\20\0\1\10\1\0\2\10\5\0\1\10\1\162"+
    "\2\10\1\0\10\10\1\0\7\10\20\0\1\10\1\0"+
    "\2\10\5\0\2\10\1\163\1\10\1\0\10\10\1\0"+
    "\7\10\33\0\1\164\42\0\1\10\1\0\2\10\5\0"+
    "\2\10\1\165\1\10\1\0\10\10\1\0\7\10\20\0"+
    "\1\10\1\0\2\10\5\0\4\10\1\166\1\167\7\10"+
    "\1\0\7\10\31\0\1\170\44\0\1\10\1\0\2\10"+
    "\5\0\1\171\3\10\1\0\10\10\1\0\7\10\35\0"+
    "\2\172\37\0\1\10\1\0\2\10\5\0\4\10\1\172"+
    "\1\173\7\10\1\0\7\10\32\0\1\174\43\0\1\10"+
    "\1\0\2\10\5\0\1\10\1\175\2\10\1\0\10\10"+
    "\1\0\7\10\20\0\1\10\1\0\2\10\5\0\4\10"+
    "\1\0\10\10\1\176\1\177\6\10\20\0\1\10\1\0"+
    "\2\10\5\0\3\10\1\200\1\0\10\10\1\0\7\10"+
    "\40\0\1\201\35\0\1\10\1\0\2\10\5\0\4\10"+
    "\1\0\2\10\1\202\5\10\1\0\7\10\40\0\1\203"+
    "\35\0\1\10\1\0\2\10\5\0\4\10\1\0\2\10"+
    "\1\204\5\10\1\0\7\10\32\0\1\205\43\0\1\10"+
    "\1\0\2\10\5\0\1\10\1\206\2\10\1\0\10\10"+
    "\1\0\7\10\35\0\2\207\37\0\1\10\1\0\2\10"+
    "\5\0\4\10\1\207\1\210\7\10\1\0\7\10\20\0"+
    "\1\10\1\0\2\10\5\0\4\10\1\211\1\212\7\10"+
    "\1\0\7\10\37\0\1\213\36\0\1\10\1\0\2\10"+
    "\5\0\4\10\1\0\1\10\1\214\6\10\1\0\7\10"+
    "\40\0\1\215\35\0\1\10\1\0\2\10\5\0\4\10"+
    "\1\0\2\10\1\216\5\10\1\0\7\10\15\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4646];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\2\11\20\1\15\11\3\1\2\0\3\11\3\1"+
    "\1\0\4\1\1\0\3\1\1\11\4\1\1\0\4\1"+
    "\1\0\6\1\1\0\4\1\1\0\3\1\1\0\3\1"+
    "\1\0\4\1\1\11\2\1\1\0\1\1\1\0\3\1"+
    "\1\0\3\1\1\0\2\1\1\0\1\1\1\11\1\1"+
    "\1\0\1\1\1\0\3\1\1\0\1\1\1\0\1\1"+
    "\1\0\1\1\1\11\1\1\1\11\1\1\1\0\2\1"+
    "\1\11\1\1\1\11\1\1\1\11\1\1\1\11\1\1"+
    "\1\0\1\1\1\0\1\1\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[142];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    String cadena="";
    String Texto="";
    public static ArrayList errorLex=new ArrayList();
	 
	 public void consola(String s){
	 
        System.out.println(s);
    }    



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexico2(java.io.Reader in) {
    this.zzReader = in;
  }



  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.out.println("Error Lexico: <<"+yytext()+">> ["+yyline+" , "+yycolumn+"]");
                                /*AcepErr datos =new AcepErr(yytext(),"ERROR LEXICO",(yyline+1),(yycolumn+1), "Simbolo no existe en el lenguaje");
                                    TablaErr.add(datos);*/
                                    //ErrorLS er = new ErrorLS("Lexico",yytext(),"",yyline,yycolumn);
                                    //HtmlClase.arrError.add(er);
                             
                                System.out.println("Error Lexico: <<"+yytext()+">> ["+yyline+" , "+yycolumn+"]");
            } 
            // fall through
          case 35: break;
          case 2: 
            { 
            } 
            // fall through
          case 36: break;
          case 3: 
            { return new Symbol(sym.digito, yyline, yycolumn,yytext());
            } 
            // fall through
          case 37: break;
          case 4: 
            { System.out.println("identificador "); return new Symbol(sym.identificador, yyline, yycolumn,yytext());
            } 
            // fall through
          case 38: break;
          case 5: 
            { System.out.println("igual"); return new Symbol(sym.igual, yyline, yycolumn,yytext());
            } 
            // fall through
          case 39: break;
          case 6: 
            { System.out.println("corA"); return new Symbol(sym.corA, yyline, yycolumn,yytext());
            } 
            // fall through
          case 40: break;
          case 7: 
            { System.out.println("corC"); return new Symbol(sym.corC, yyline, yycolumn,yytext());
            } 
            // fall through
          case 41: break;
          case 8: 
            { System.out.println("coma"); return new Symbol(sym.coma, yyline, yycolumn,yytext());
            } 
            // fall through
          case 42: break;
          case 9: 
            { System.out.println("llaveA"); return new Symbol(sym.llaveA, yyline, yycolumn,yytext());
            } 
            // fall through
          case 43: break;
          case 10: 
            { System.out.println("llaveC"); return new Symbol(sym.llaveC, yyline, yycolumn,yytext());
            } 
            // fall through
          case 44: break;
          case 11: 
            { System.out.println("puntocoma"); return new Symbol(sym.puntocoma, yyline, yycolumn,yytext());
            } 
            // fall through
          case 45: break;
          case 12: 
            { System.out.println("parA"); return new Symbol(sym.parA, yyline, yycolumn,yytext());
            } 
            // fall through
          case 46: break;
          case 13: 
            { System.out.println("parentesisC"); return new Symbol(sym.parC, yyline, yycolumn,yytext());
            } 
            // fall through
          case 47: break;
          case 14: 
            { System.out.println("menorque"); return new Symbol(sym.menorque, yyline, yycolumn,yytext());
            } 
            // fall through
          case 48: break;
          case 15: 
            { System.out.println("mayorque"); return new Symbol(sym.mayorque, yyline, yycolumn,yytext());
            } 
            // fall through
          case 49: break;
          case 16: 
            { System.out.println("desigual"); return new Symbol(sym.desigual, yyline, yycolumn,yytext());
            } 
            // fall through
          case 50: break;
          case 17: 
            { System.out.println("dospuntos"); return new Symbol(sym.dospuntos, yyline, yycolumn,yytext());
            } 
            // fall through
          case 51: break;
          case 18: 
            { yybegin(YYINITIAL);
            } 
            // fall through
          case 52: break;
          case 19: 
            { /* ignore white space. */
            } 
            // fall through
          case 53: break;
          case 20: 
            { System.out.println("cadena "); return new Symbol(sym.cadena, yyline, yycolumn,yytext());
            } 
            // fall through
          case 54: break;
          case 21: 
            { yybegin(COMENT_SIMPLE);
            } 
            // fall through
          case 55: break;
          case 22: 
            { yybegin(COMENT_MULTI);
            } 
            // fall through
          case 56: break;
          case 23: 
            { return new Symbol(sym.decimal, yyline, yycolumn,yytext());
            } 
            // fall through
          case 57: break;
          case 24: 
            { System.out.println("sumar"); return new Symbol(sym.sumar, yycolumn, yyline, yytext());
            } 
            // fall through
          case 58: break;
          case 25: 
            { System.out.println("varcadena"); return new Symbol(sym.tcadena, yycolumn, yyline, yytext());
            } 
            // fall through
          case 59: break;
          case 26: 
            { System.out.println("Contar"); return new Symbol(sym.contar, yycolumn, yyline, yytext());
            } 
            // fall through
          case 60: break;
          case 27: 
            { System.out.println("archivo"); return new Symbol(sym.archivo, yycolumn, yyline, yytext());
            } 
            // fall through
          case 61: break;
          case 28: 
            { System.out.println("ContarSi"); return new Symbol(sym.contarSi, yycolumn, yyline, yytext());
            } 
            // fall through
          case 62: break;
          case 29: 
            { System.out.println("Imprimir"); return new Symbol(sym.imprimir, yycolumn, yyline, yytext());
            } 
            // fall through
          case 63: break;
          case 30: 
            { System.out.println("Numerico"); return new Symbol(sym.numerico, yycolumn, yyline, yytext());
            } 
            // fall through
          case 64: break;
          case 31: 
            { System.out.println("Promedio"); return new Symbol(sym.promedio, yycolumn, yyline, yytext());
            } 
            // fall through
          case 65: break;
          case 32: 
            { System.out.println("graficar"); return new Symbol(sym.graficar, yycolumn, yyline, yytext());
            } 
            // fall through
          case 66: break;
          case 33: 
            { System.out.println("ObtenerSi"); return new Symbol(sym.obtenerSi, yycolumn, yyline, yytext());
            } 
            // fall through
          case 67: break;
          case 34: 
            { System.out.println("leerArchivo"); return new Symbol(sym.leerArchivo, yycolumn, yyline, yytext());
            } 
            // fall through
          case 68: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
