
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador2;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int cadena = 5;
  public static final int decimal = 4;
  public static final int coma = 21;
  public static final int promedio = 12;
  public static final int archivo = 8;
  public static final int imprimir = 10;
  public static final int sumar = 6;
  public static final int contarSi = 9;
  public static final int numerico = 11;
  public static final int corC = 20;
  public static final int llaveC = 18;
  public static final int digito = 3;
  public static final int menorque = 25;
  public static final int corA = 19;
  public static final int igual = 16;
  public static final int EOF = 0;
  public static final int llaveA = 17;
  public static final int desigual = 27;
  public static final int puntocoma = 22;
  public static final int obtenerSi = 14;
  public static final int mayorque = 26;
  public static final int parC = 24;
  public static final int error = 1;
  public static final int contar = 7;
  public static final int parA = 23;
  public static final int leerArchivo = 15;
  public static final int graficar = 13;
  public static final int dospuntos = 28;
  public static final int identificador = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "identificador",
  "digito",
  "decimal",
  "cadena",
  "sumar",
  "contar",
  "archivo",
  "contarSi",
  "imprimir",
  "numerico",
  "promedio",
  "graficar",
  "obtenerSi",
  "leerArchivo",
  "igual",
  "llaveA",
  "llaveC",
  "corA",
  "corC",
  "coma",
  "puntocoma",
  "parA",
  "parC",
  "menorque",
  "mayorque",
  "desigual",
  "dospuntos"
  };
}

