/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafico;

import Analizador.Lexico;
import Analizador.Sintactico;
import Analizador2.Lexico2;
import Analizador2.Sintactico2;
import java.awt.TextArea;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.StringReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import Objetos.Puente;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;

/**
 *
 * @author Chriss Ramos
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    JFileChooser seleccionar = new JFileChooser();
    File archivo;
    FileInputStream entrada;
    FileOutputStream salida;
    public Ventana() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtConsola = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtConsola.setBackground(new java.awt.Color(0, 0, 0));
        txtConsola.setColumns(20);
        txtConsola.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txtConsola.setForeground(new java.awt.Color(51, 204, 0));
        txtConsola.setRows(5);
        jScrollPane1.setViewportView(txtConsola);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Consola");

        jButton1.setText("REP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("dat");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jMenu3.setText("Archivo");

        jMenuItem1.setText("Abrir .dat");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem5.setText("Abrir .rep");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem2.setText("Guardar");
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Guardar Como");
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Reportes");

        jMenuItem4.setText("Reporte HTML");
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 967, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 977, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(15, 15, 15)))
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        //primero abrir el archivo, guardar nombre, el contenido del txt meterlo a un textarea
        File f;
        FileReader lectorArchivo;

//        if (seleccionar.showDialog(null,"Abrir")== JFileChooser.APPROVE_OPTION) {
//            archivo = seleccionar.getSelectedFile();
//            if (archivo.getName().endsWith("dat")) {
//                String documento = abrirArchivo(archivo);
//                String titulo = seleccionar.getName(archivo);
//                TextArea txtArea = new TextArea();
//                txtArea.setText(documento);
//                panelPrincipal.addTab(titulo, txtArea);
//            }else{
//                        JOptionPane.showMessageDialog(null, "Archivo no compatible");
//            }
//            
//                    
//        }
        
        if(seleccionar.showDialog(null, "Abrir") == JFileChooser.APPROVE_OPTION){
            //archivo = seleccionar.getSelectedFile();
            try{
                
                f = seleccionar.getSelectedFile();
                JOptionPane.showMessageDialog(null, "Seabrrira: " + f.getName());
                lectorArchivo = new FileReader(f);
                BufferedReader br = new BufferedReader(lectorArchivo);
                //BufferedReader br2 = new BufferedReader(new InputStreamReader(seleccionar.getSelectedFile(), "ISO-8859-1"));
                String lectura = "";
                String aux="";
                while (true) {
                    aux=br.readLine();
                    if(aux!=null)
                        lectura=lectura+aux+"\n";
                    else 
                        break;
                    
                }
                br.close();
                lectorArchivo.close();
                String titulo = seleccionar.getName(f);
                TextArea txtArea = new TextArea();
                txtArea.setText(lectura);
                panelPrincipal.addTab(titulo, txtArea);
             }catch (FileNotFoundException ex) {
                Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            

        }
        
        //panelPrincipal.addTab("Nuevo Archivo", new TextArea());
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           int pestAct = panelPrincipal.getSelectedIndex();
//         JOptionPane.showMessageDialog(null, "hay " + pest + " pestanias y esta en la pest:" + pestAct);
         TextArea texto = new TextArea();
         //texto = panelPrincipal.getComponent(pestAct);
        texto= (TextArea)panelPrincipal.getComponent(pestAct);
        //txtConsola.setText(texto.getText());
       try{
            Sintactico2 sin = new Sintactico2(
                new Lexico2(new BufferedReader (new StringReader(texto.getText()))));
            sin.parse();
        }catch(Exception e){
            Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, e);
        }
        imprimirConsola();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed

         File f;
        FileReader lectorArchivo;
//        if (seleccionar.showDialog(null,"Abrir")== JFileChooser.APPROVE_OPTION) {
//            
//            archivo = seleccionar.getSelectedFile();
//            if (archivo.getName().endsWith("rep")) {
//                String documento = abrirArchivo(archivo);
//                String titulo = seleccionar.getName(archivo);
//                TextArea txtArea = new TextArea();
//                txtArea.setText(documento);
//                panelPrincipal.addTab(titulo, txtArea);
//            }else{
//                        JOptionPane.showMessageDialog(null, "Archivo no compatible");
//            }
//            
//                    
//        }


        if(seleccionar.showDialog(null, "Abrir") == JFileChooser.APPROVE_OPTION){
            //archivo = seleccionar.getSelectedFile();
            try{
                
                f = seleccionar.getSelectedFile();
                JOptionPane.showMessageDialog(null, "Seabrrira: " + f.getName());
                lectorArchivo = new FileReader(f);
                BufferedReader br = new BufferedReader(lectorArchivo);
                //BufferedReader br2 = new BufferedReader(new InputStreamReader(seleccionar.getSelectedFile(), "ISO-8859-1"));
                String lectura = "";
                String aux="";
                while (true) {
                    aux=br.readLine();
                    if(aux!=null)
                        lectura=lectura+aux+"\n";
                    else 
                        break;
                    
                }
                br.close();
                lectorArchivo.close();
                String titulo = seleccionar.getName(f);
                TextArea txtArea = new TextArea();
                txtArea.setText(lectura);
                panelPrincipal.addTab(titulo, txtArea);
             }catch (FileNotFoundException ex) {
                Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            

        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed
    public void imprimirConsola(){
        System.err.println("en ventana>" + Puente.variableConsola);
        txtConsola.setText(Puente.variableConsola);
        
    }
    
    public void clavesArr(){
        JOptionPane.showMessageDialog(null, "Hay: " + Puente.arrClaves.size() + " claves" );
        
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          // TODO add your handling code here:
          int pestAct = panelPrincipal.getSelectedIndex();
//         JOptionPane.showMessageDialog(null, "hay " + pest + " pestanias y esta en la pest:" + pestAct);
         TextArea texto = new TextArea();
         //texto = panelPrincipal.getComponent(pestAct);
        texto= (TextArea)panelPrincipal.getComponent(pestAct);
        //txtConsola.setText(texto.getText());
       try{
            Sintactico sin = new Sintactico(
                new Lexico(new BufferedReader (new StringReader(texto.getText()))));
            sin.parse();
        }catch(Exception e){
            //Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, e);
            e.printStackTrace();
        }
        clavesArr();
        Puente.mostrarDatos();
    }//GEN-LAST:event_jButton2ActionPerformed
    public String abrirArchivo(File archivo){
        
        String documento="";
        
        try{
            entrada=new FileInputStream(archivo);
            int ascii;
            while ((ascii=entrada.read())!=-1) {
                char caracter=(char)ascii;
                documento+=caracter;
            }
        }catch(Exception e){
        
        }
        return documento;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane panelPrincipal;
    private javax.swing.JTextArea txtConsola;
    // End of variables declaration//GEN-END:variables
}
